import { DatabaseSync, backup } from "node:sqlite";
import { RouterEngine } from "../server/router.mjs";
import { repairAstraCosts } from "../server/repair-astra-costs.mjs";
const dir = "C:/Users/lylens/AppData/Roaming/com.chen.codex-router";
const db = new DatabaseSync(`${dir}/router.sqlite`);
const path = `D:/ks/16.mimi/work/router-before-cost-repair-${Date.now()}.sqlite`;
await backup(db, path);
console.log("Backup:", path);
const engine = new RouterEngine(db, dir, () => {});
console.log(repairAstraCosts(db, engine));
console.log("Second run:", repairAstraCosts(db, engine));
console.log(db.prepare("SELECT cost_status,COUNT(*) count,SUM(total_cost_usd) usd FROM requests WHERE requested_model=? GROUP BY cost_status").all("gpt-6-astra"));
db.close();
